# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHnkSj2mmo6yB0HD1p0ogdcM2p0PfgAp
"""

import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import LocallyLinearEmbedding, TSNE
from sklearn.metrics.pairwise import cosine_similarity

class StockEmbeddingPipeline:
    def __init__(self, tickers, start_date="2020-01-01", end_date="2025-01-01"):
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.aligned_tickers = []
        self.X_scaled = None
        self.models = {}
        self.embeddings = {}

    def fetch_and_prepare_data(self):
        """Downloads stock data, handles missing values, and standardizes it."""
        print(f"Downloading data for {len(self.tickers)} tickers...")
        data = yf.download(self.tickers, start=self.start_date, end=self.end_date)['Close']

        data = data.ffill().bfill()
        self.aligned_tickers = data.columns.tolist()

        X = data.T.values

        scaler = StandardScaler()
        self.X_scaled = scaler.fit_transform(X.T).T
        print("Data preparation complete.")

    def train_embedding(self, method="LLE", **kwargs):
        """
        Trains the embedding algorithm and stores the transformed coordinates.
        Supports passing custom parameters (e.g., n_components, perplexity) via kwargs.
        """
        if self.X_scaled is None:
            raise ValueError("Data not prepared. Call fetch_and_prepare_data() first.")

        method = method.upper()
        print(f"Running {method}...")

        if method == "LLE":
            params = {"n_neighbors": 5, "n_components": 2, "random_state": 1}
            params.update(kwargs)
            model = LocallyLinearEmbedding(**params)

        elif method == "TSNE":
            params = {"n_components": 3, "perplexity": 3, "random_state": 1}
            params.update(kwargs)
            model = TSNE(**params)

        else:
            raise ValueError("Unsupported method. Choose 'LLE' or 'TSNE'.")

        self.models[method] = model
        self.embeddings[method] = model.fit_transform(self.X_scaled)
        print(f"[{method}] Training and coordinate transformation complete.")

    def predict_similarities(self, method):
        """
        'Predicts' the relationships by computing the cosine similarity
        matrix from the trained embeddings.
        """
        method = method.upper()
        if method not in self.embeddings:
            raise ValueError(f"No embeddings found for {method}. Call train_embedding('{method}') first.")

        sim_matrix = cosine_similarity(self.embeddings[method])
        df_sim = pd.DataFrame(sim_matrix, index=self.aligned_tickers, columns=self.aligned_tickers)

        return df_sim

if __name__ == "__main__":
    tickers_list = ["AAPL","MSFT","GOOGL","AMZN","NVDA","TSLA","JPM","XOM","WMT","JNJ","SPY"]

    pipeline = StockEmbeddingPipeline(tickers_list)

    pipeline.fetch_and_prepare_data()

    pipeline.train_embedding(method="LLE", n_neighbors=5, n_components=2)
    pipeline.train_embedding(method="TSNE", perplexity=3, n_components=3)

    df_sim_lle = pipeline.predict_similarities(method="LLE")
    df_sim_tsne = pipeline.predict_similarities(method="TSNE")

    print("\n--- LLE Cosine Similarity Matrix (Top 5) ---")
    print(df_sim_lle.iloc[:5, :5])

    print("\n--- t-SNE Cosine Similarity Matrix (Top 5) ---")
    print(df_sim_tsne.iloc[:5, :5])