# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHnkSj2mmo6yB0HD1p0ogdcM2p0PfgAp
"""

import os
import json
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import LocallyLinearEmbedding, TSNE
from sklearn.metrics.pairwise import cosine_similarity

class StockEmbeddingPipeline:
    def __init__(self, data_dir="/data"):
        self.data_dir = data_dir
        self.aligned_tickers = []
        self.X_scaled = None
        self.models = {}
        self.embeddings = {}

    def load_and_prepare_data(self):
        """
        Read data from JSONL files and standardize.
        """
        print(f"Loading data from {self.data_dir}...")
        all_series = {}

        if not os.path.exists(self.data_dir):
            raise FileNotFoundError(f"Directory {self.data_dir} not found.")

        for filename in os.listdir(self.data_dir):
            if filename.endswith('.jsonl'):
                ticker = filename.replace('.jsonl', '')
                filepath = os.path.join(self.data_dir, filename)

                dates = []
                closes = []

                with open(filepath, 'r') as f:
                    for line in f:
                        if not line.strip(): continue
                        record = json.loads(line)
                        dates.append(pd.to_datetime(record['timestamp'], unit='ms'))
                        closes.append(record['close'])

                all_series[ticker] = pd.Series(closes, index=dates)

        if not all_series:
            raise ValueError(f"No valid JSONL files found in {self.data_dir}.")

        print(f"Successfully loaded {len(all_series)} tickers. Merging...")

        data = pd.DataFrame(all_series)
        data = data.sort_index()
        data = data.ffill().bfill()
        self.aligned_tickers = data.columns.tolist()

        X = data.T.values

        scaler = StandardScaler()
        self.X_scaled = scaler.fit_transform(X.T).T
        print("Data preparation complete.")

    def train_embedding(self, method="LLE", **kwargs):
        if self.X_scaled is None:
            raise ValueError("Data not prepared. Call load_and_prepare_data() first.")

        method = method.upper()
        print(f"Running {method}...")

        if method == "LLE":
            params = {"n_neighbors": 5, "n_components": 2, "random_state": 42}
            params.update(kwargs)
            model = LocallyLinearEmbedding(**params)

        elif method == "TSNE":
            params = {"n_components": 3, "perplexity": 3, "random_state": 42}
            params.update(kwargs)
            model = TSNE(**params)

        else:
            raise ValueError("Unsupported method. Choose 'LLE' or 'TSNE'.")

        self.models[method] = model
        self.embeddings[method] = model.fit_transform(self.X_scaled)
        print(f"[{method}] Training and coordinate transformation complete.")

    def predict_similarities(self, method):
        method = method.upper()
        if method not in self.embeddings:
            raise ValueError(f"No embeddings found for {method}. Call train_embedding('{method}') first.")

        sim_matrix = cosine_similarity(self.embeddings[method])
        df_sim = pd.DataFrame(sim_matrix, index=self.aligned_tickers, columns=self.aligned_tickers)

        return df_sim

if __name__ == "__main__":
    pipeline = StockEmbeddingPipeline(data_dir="/data")

    pipeline.load_and_prepare_data()

    pipeline.train_embedding(method="LLE", n_neighbors=5, n_components=2)
    pipeline.train_embedding(method="TSNE", perplexity=30, n_components=3)

    df_sim_lle = pipeline.predict_similarities(method="LLE")
    df_sim_tsne = pipeline.predict_similarities(method="TSNE")

    print("\n--- LLE Cosine Similarity Matrix (Top 5) ---")
    print(df_sim_lle.iloc[:5, :5])

    print("\n--- t-SNE Cosine Similarity Matrix (Top 5) ---")
    print(df_sim_tsne.iloc[:5, :5])